# Generated by Django 4.2.5 on 2024-08-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('new_film', 'Mew film'), ('bookmarks', 'Bookmarks'), ('info', 'Info')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=255)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('user_group', models.CharField(blank=True, max_length=255, null=True)),
                ('template', models.TextField(help_text='Шаблон сообщения для email или текста')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
