# Generated by Django 4.2.5 on 2024-08-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationtemplate_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_group',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('sign_up', 'Sign up'), ('review_like', 'Review like'), ('new_film', 'New film'), ('new_episode', 'New episode'), ('bookmarks', 'Bookmarks'), ('info', 'Info')], max_length=20),
        ),
    ]
