# Generated by Django 4.2.5 on 2024-08-15 13:22
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allowed_email', models.BooleanField(default=True)),
                ('allowed_push', models.BooleanField(default=True)),
                ('time_zone', models.CharField(max_length=10)),
            ],
        ),
    ]
