# Generated by Django 4.2.5 on 2024-08-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='template',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
