# Generated by Django 5.0 on 2024-08-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notificationtemplate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('initial', 'Initial'), ('sent', 'Sent'), ('error', 'Error')], default='INITIAL', max_length=20),
        ),
    ]
